---
- name: Update APT and download OpenJDK 11 packages
  hosts: all 
  become: true
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: only update if older than 1 hour

    - name: Create directory for OpenJDK 11 JDK .deb files
      file:
        path: /home/bastion/openjdk-11-jdk
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'

    - name: Create directory for OpenJDK 11 JRE .deb files
      file:
        path: /home/bastion/openjdk-11-jre
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'
        
    - name: Download .deb files
      shell: |
        cd /home/bastion/openjdk-11-jdk && \
        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
          --no-conflicts --no-breaks --no-replaces --no-enhances \
          --no-pre-depends openjdk-11-jdk | grep '^\w') && \
        cd /home/bastion/openjdk-11-jre && \
        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
          --no-conflicts --no-breaks --no-replaces --no-enhances \   
          --no-pre-depends openjdk-11-jre | grep "^\w")
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: noninteractive

- name: Sync jdk and jre folders from bastion to c2 server
  hosts: "{{ c2server_ipv4 }}"
  gather_facts: false
  tasks:
    - name: Sync jdk folder from bastion to c2 server
      synchronize:
        src: /home/bastion/openjdk-11-jdk
        dest: /home/c2server/openjdk-11-jdk
        mode: pull
        rsync_opts:
          - "--rsh=ssh -i /home/bastion/.ssh/internal.pem -l c2server -o StrictHostKeyChecking=no"
        delegate_to: "{{ bastion_ipv6 }}"
