---
- name: Install Dependencies on C2 Server
  hosts: all 
  become: true
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: only update if older than 1 hour

    - name: Create JDK dir on Bastion
      file:
        path: /home/bastion/openjdk-11-jdk
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'

    - name: Create JRE dir on Bastion
      file:
        path: /home/bastion/openjdk-11-jre
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'
    
    - name: Create Other Dependas on Bastion
      file:
        path: /home/bastion/other-dependas
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'

#    - name: Download .deb files onto Bastion
#      shell: |
#        cd /home/bastion/openjdk-11-jdk && \
#        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
#          --no-conflicts --no-breaks --no-replaces --no-enhances \
#          --no-pre-depends openjdk-11-jdk | grep '^\w') && \
#        cd /home/bastion/openjdk-11-jre && \
#        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
#          --no-conflicts --no-breaks --no-replaces --no-enhances \   
#          --no-pre-depends openjdk-11-jre | grep "^\w") && \
#        cd /home/bastion/other-dependas && \
#        apt-get download iptables unzip screen net-tools tcpdump socat
#      args:
#        executable: /bin/bash
#      environment:
#        DEBIAN_FRONTEND: noninteractive
#
#    - name: Transfer files to C2 Server
#      shell: |
#        # jdk
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "mkdir -p /home/c2server/openjdk-11-jdk" && \
#        scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/openjdk-11-jdk/*.deb \
#          c2server@{{ c2_ipv4 }}:/home/c2server/openjdk-11-jdk && \ 
#        
#        # jre  
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "mkdir -p /home/c2server/openjdk-11-jre" && \
#        scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/openjdk-11-jre/*.deb \
#          c2server@{{ c2_ipv4 }}:/home/c2server/openjdk-11-jre && \
#        
#        # other dependas
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "mkdir -p /home/c2server/other-dependas" && \
#          scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/other-dependas/*.deb \
#          c2server@{{ c2_ipv4 }}:/home/c2server/other-dependas
#      args:
#        executable: /bin/bash
#
#   - name: Install .deb files
#      shell: |
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "sudo dpkg -i /home/c2server/other-dependas/*.deb" 
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "sudo dpkg -i /home/c2server/openjdk-11-jdk/*.deb"
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "sudo dpkg -i /home/c2server/openjdk-11-jre/*.deb"
#      args:
#        executable: /bin/bash
#
#    - name: Install 7zip
#      apt:
#        name: 7zip
#        state: present
#        update_cache: yes
#
#    - name: Download and Set up Cobalt Strike 4.9.1
#      get_url:
#        url: "https://cs-v491.s3.dualstack.us-west-1.amazonaws.com/cs-4.9.1.7z"
#        dest: /home/bastion/cs-4.9.1.7z
#        mode: '0644'
#        owner: bastion
#        group: bastion
    
    - name: Transfer Cobalt Strike from Bastion to C2
      shell: |
       scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/cs-4.9.1.7z \
          c2server@{{ c2_ipv4 }}:/home/c2server
      args:
        executable: /bin/bash
