---
- name: Install Dependencies on C2 Server
  hosts: all 
  become: true
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: only update if older than 1 hour

    - name: Create JDK dir on Bastion
      file:
        path: /home/bastion/openjdk-11-jdk
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'

    - name: Create JRE dir on Bastion
      file:
        path: /home/bastion/openjdk-11-jre
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'
        
    - name: Download .deb files onto Bastion
      shell: |
        cd /home/bastion/openjdk-11-jdk && \
        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
          --no-conflicts --no-breaks --no-replaces --no-enhances \
          --no-pre-depends openjdk-11-jdk | grep '^\w') && \
        cd /home/bastion/openjdk-11-jre && \
        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
          --no-conflicts --no-breaks --no-replaces --no-enhances \   
          --no-pre-depends openjdk-11-jre | grep "^\w")
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Transfer files to C2 Server
      shell: >
        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
          "mkdir -p /home/c2server/openjdk-11-jdk" && \
          scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/openjdk-11-jdk/*.deb \
          c2server@{{ c2_ipv4 }}:/home/c2server/openjdk-11-jdk 
         ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
          "mkdir -p /home/c2server/openjdk-11-jre" && \
          scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/openjdk-11-jre/*.deb \
          c2server@{{ c2_ipv4 }}:/home/c2server/openjdk-11-jre
      args:
        executable: /bin/bash



