---
- name: Install Dependencies on C2 Server
  hosts: all 
  become: true 
#  vars_prompt:
#    - name: PASS
#      prompt: "Enter 7z Password"
#      private: yes
  tasks: 
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: only update if older than 1 hour

#    - name: Create JDK dir on Bastion
#      file:
#        path: /home/bastion/openjdk-11-jdk
#        state: directory
#        owner: bastion
#        group: bastion
#        mode: '0755'
#
#    - name: Create JRE dir on Bastion
#      file:
#        path: /home/bastion/openjdk-11-jre
#        state: directory
#        owner: bastion
#        group: bastion
#        mode: '0755'
#    
#    - name: Create C2 Dependas on Bastion
#      file:
#        path: /home/bastion/c2-dependas
#        state: directory
#        owner: bastion
#        group: bastion
#        mode: '0755'
#
    - name: Create Redirector Dependas on Bastion
      file:
        path: /home/bastion/re-dependas
        state: directory
        owner: bastion
        group: bastion
        mode: '0755'

    - name: Download .deb files onto Bastion
      shell: |
        cd /home/bastion/re-dependas && \
        apt-get download iptables-persistent netfilter-persistent && \
        cp /home/bastion/c2-dependas/iptables* /home/bastion/re-dependas
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: noninteractive

#        cd /home/bastion/openjdk-11-jdk && \
#        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
#          --no-conflicts --no-breaks --no-replaces --no-enhances \
#          --no-pre-depends openjdk-11-jdk | grep '^\w') && \
#        cd /home/bastion/openjdk-11-jre && \
#        apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
#          --no-conflicts --no-breaks --no-replaces --no-enhances \   
#          --no-pre-depends openjdk-11-jre | grep "^\w") && \
#        cd /home/bastion/c2-dependas && \
#        apt-get download iptables unzip screen net-tools tcpdump socat p7zip-full && \
#        cd /home/bastion/re-dependas && \
#        apt-get download iptables-persistent
#      args:
#        executable: /bin/bash
#      environment:
#        DEBIAN_FRONTEND: noninteractive
#
    - name: Transfer files to C2 Server and Redirector
      shell: |
        # re dependas
        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no redirector@{{ re_ipv4 }} \
          "mkdir -p /home/redirector/re-dependas" && \
          scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/re-dependas/*.deb \
          redirector@{{ re_ipv4 }}:/home/redirector/re-dependas
      args:
        executable: /bin/bash
#        # jdk
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "mkdir -p /home/c2server/openjdk-11-jdk" && \
#        scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/openjdk-11-jdk/*.deb \
#          c2server@{{ c2_ipv4 }}:/home/c2server/openjdk-11-jdk && \ 
#        
#        # jre  
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "mkdir -p /home/c2server/openjdk-11-jre" && \
#        scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/openjdk-11-jre/*.deb \
#          c2server@{{ c2_ipv4 }}:/home/c2server/openjdk-11-jre && \
#        
#        # c2 dependas
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "mkdir -p /home/c2server/c2-dependas" && \
#          scp -i .ssh/internal.pem -o StrictHostKeyChecking=no -v /home/bastion/c2-dependas/*.deb \
#          c2server@{{ c2_ipv4 }}:/home/c2server/c2-dependas
#
        
#
    - name: Install .deb files
      shell: |
        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no redirector@{{ re_ipv4 }} \
        "sudo sh -c 'echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections && echo iptables-persistent iptables-persistent/autosave_v6 boolean false | debconf-set-selections && DEBIAN_FRONTEND=noninteractive && dpkg -i /home/redirector/re-dependas/*.deb'"

      args:
        executable: /bin/bash
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "sudo dpkg -i /home/c2server/c2-dependas/*.deb" 
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "sudo dpkg -i /home/c2server/openjdk-11-jdk/*.deb"
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "sudo dpkg -i /home/c2server/openjdk-11-jre/*.deb"

#
#    - name: Install p7zip-full
#      apt:
#        name: p7zip-full
#        state: present
#        update_cache: yes

#    - name: Download and Set up Cobalt Strike 4.9.1
#      get_url:
#        url: "https://cs-v491.s3.dualstack.us-west-1.amazonaws.com/cs-4.9.1.7z"
#        dest: /home/bastion/cs-4.9.1.7z
#        mode: '0644'
#        owner: bastion
#        group: bastion
# 
#    - name: Unzip CobaltStrike
#      shell: |
#        ssh -i .ssh/internal.pem -o StrictHostKeyChecking=no c2server@{{ c2_ipv4 }} \
#          "7z x -p{{PASS}} /home/c2server/cs-4.9.1.7z -o/home/c2server/"
#      args:
#          executable: /bin/bash

